version: "3"

tasks:
  default:
    cmds:
      - task --list

  fmt:
    desc: Format Go source files
    cmds:
      - go fmt ./...

  vet:
    desc: Run go vet across the module
    cmds:
      - go vet ./...

  lint:
    desc: Run golangci-lint and gopls diagnostics
    deps:
      - fmt
      - vet
    cmds:
      - golangci-lint run ./...
      - find . -name "*.go" -type f | xargs gopls check -severity=hint || true
    ignore_error: true

  gopls-check:
    desc: Run gopls diagnostics only (includes modernize analyzer)
    cmds:
      - find . -name "*.go" -type f | xargs gopls check -severity=hint

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  build:
    desc: Build the envlock CLI
    cmds:
      - mkdir -p bin
      - go build -o bin/envlock .

  build-server:
    desc: Build the envlock server (dev scaffold)
    cmds:
      - mkdir -p bin
      - go build -o bin/envlock-server ./cmd/server

  install:
    desc: Install envlock into /opt/homebrew/bin or /usr/local/bin
    deps:
      - build
    cmds:
      - |
        if [ -d /opt/homebrew/bin ]; then
          install -m 0755 bin/envlock /opt/homebrew/bin/envlock
        else
          install -m 0755 bin/envlock /usr/local/bin/envlock
        fi

  run:
    desc: "Run envlock locally (pass args with: task run -- --help)"
    cmds:
      - go run . {{.CLI_ARGS}}

  run-server:
    desc: "Run envlock server locally (pass args with: task run-server -- ...)"
    cmds:
      - go run ./cmd/server {{.CLI_ARGS}}

  clean:
    desc: Remove built binary
    cmds:
      - rm -f bin/envlock

  release:
    desc: Commit Push Commit to Github
    cmds:
      - mdrelease
